### ISSUE TITLE
（issueの練習）好きな食べ物について聞き忘れてた

### ISSUE THREAD

**Issue by sjyama** [sjyama/git_practice_201901#8]

**Comment by sjyama** [comment]
ここでissue（課題）について協議できるのね？
てすとてすと。

**Comment by sjyama** [comment]
@F-Yuki メンションとかできちゃう感じかな。
好きな食べ物以外に、聞き忘れてる（書き忘れてる）こと無いかな？ｗ

**Comment by F-Yuki** [comment]
@sjyama さん、issue の作成、ありがとうございます。
好きな食べ物は以下３つ

- カレーライス（昔ながらの日本のカレーライス限定）

- ハンバーグ（和風ソースorテリヤキソース）

-餃子

好きな食べ物以外に、聞き忘れてる（書き忘れてる）ことは
スタンダードに趣味とかですかねw

こんな感じで良いのでしょうか？

**Comment by tassssra** [comment]
issue作成ありがとうございます！

**Comment by tassssra** [comment]
@sjyama 
課題についての意見を忘れてました…
「今勉強中のこと、教材について」はどうでしょうか

>最終的にはソース「introduce.txt」または「README」を修正して、確認後issue close って流れ
はい、私もその認識です！

**Comment by sjyama** [comment]
@tassssra 追記ありがとうございます！

**Comment by sjyama** [comment]
@tassssra しまった！間違ってクローズボタン押してしまいました！ｍ
reopenできたようなので一旦、OKかな？（失礼しました）

＞「今勉強中のこと、教材について」はどうでしょうか
それもいいですね！README修正してみようかしら。

**Comment by sjyama** [comment]
このissueについては一旦READMEに反映させ、プルリク→マージまで完了しましたのでクローズとしましょうかね。

どなたか練習がてらクローズ（”Close and comment” ボタンから）をお願いします〜^^
あと可能であればprojects タブのタスクも「完了分」に移動させていただければ◎
（早いものがちです〜★お気軽にどうぞ）

**Comment by tassssra** [comment]
それではクローズさせていただきます！
段取り完璧ですね〜
行動力、当事者意識もマジリスペクトです(私は指示通りやってるだけ…w)

**Comment by sjyama** [comment]
@tassssra （Closed issueですが追記）
いえいえ、できることからトライするのみです◎
お付き合いいただきありがとうございます！自分も勉強させてもらってます！ｍ
